name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build for multiple platforms
      run: |
        # Build for Linux x86_64
        GOOS=linux GOARCH=amd64 go build -o aws-cost-exporter-linux-amd64 .
        
        # Build for Linux ARM64
        GOOS=linux GOARCH=arm64 go build -o aws-cost-exporter-linux-arm64 .
        
        # Build for macOS x86_64
        GOOS=darwin GOARCH=amd64 go build -o aws-cost-exporter-darwin-amd64 .
        
        # Build for macOS ARM64
        GOOS=darwin GOARCH=arm64 go build -o aws-cost-exporter-darwin-arm64 .
        
        # Build for Windows x86_64
        GOOS=windows GOARCH=amd64 go build -o aws-cost-exporter-windows-amd64.exe .

    - name: Log in to the Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Create Dockerfile
      run: |
        cat > Dockerfile << 'EOF'
        FROM scratch
        COPY aws-cost-exporter-linux-amd64 /aws-cost-exporter
        EXPOSE 8080
        ENTRYPOINT ["/aws-cost-exporter"]
        EOF

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          aws-cost-exporter-linux-amd64
          aws-cost-exporter-linux-arm64
          aws-cost-exporter-darwin-amd64
          aws-cost-exporter-darwin-arm64
          aws-cost-exporter-windows-amd64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}